---
sidebar: sidebar 
permalink: scpivs44_minimum_ontap_privileges_required.html 
keywords:  
summary: Die erforderlichen Mindestberechtigungen für ONTAP variieren je nach SnapCenter Plug-ins, die Sie zur Datensicherung verwenden. 
---
= ONTAP-Berechtigungen erforderlich
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die erforderlichen Mindestberechtigungen für ONTAP variieren je nach SnapCenter Plug-ins, die Sie zur Datensicherung verwenden.



== Mindestberechtigungen für ONTAP erforderlich

Für alle SnapCenter Plug-ins sind die folgenden Mindestberechtigungen erforderlich.

|===
| Befehle für All-Access: Mindestberechtigungen erforderlich für ONTAP 8.3 und höher 


| Event Generate-AutoSupport-log 


| Job-Verlauf wird angezeigt
Job beenden 


| lun
lun erstellen
lun löschen
lun Initiatorgruppe hinzufügen
lun-Initiatorgruppe wird erstellt
lun-Initiatorgruppe löschen
lun igroup umbenennen
lun-Initiatorgruppe wird angezeigt
lun Mapping Add-Reporting-Nodes
lun-Zuordnung erstellen
lun-Zuordnung löschen
lun Mapping remove-Reporting-Nodes
lun-Zuordnung wird angezeigt
lun ändern
lun-Verschiebung in Volume
lun ist offline
lun ist online
lun Persistent-Reservierung löschen
die lun-Größe wird geändert
lun seriell
lun anzeigen 


| snapmirror Listenziele
SnapMirror Richtlinie Add-Rule
änderungsregel für snapmirror
Remove-Rule für snapmirror-Richtlinie
snapmirror-Richtlinie anzeigen
snapmirror Wiederherstellung
snapmirror zeigen
snapmirror Vorgeschichte
snapmirror Update
snapmirror Update-ls-Set 


| Version 


| Erstellung von Volume-Klonen
Klon von Volume anzeigen
Split-Start des Volume-Klons
Split-Stopp für Volume-Klon
Volume erstellen
Volume destroy
Erstellen eines Volume-Dateiklonen
Show-Disk-Nutzung für Volume-Dateien
Volume ist offline
Das Volume ist online
Volume-Änderung
Erstellen von Volume-qtree
Volume qtree löschen
Änderung des Volume-qtree
Volume-qtree anzeigen
Volume-Einschränkung
Volumen anzeigen
Erstellen von Volume-Snapshots
Volume Snapshot löschen
Ändern des Volume-Snapshots
Umbenennung von Volume-Snapshots
Wiederherstellung von Volume Snapshots
Restore-Datei für Volume Snapshots
Volume-Snapshot werden angezeigt
Volume-Aufhängung nicht verfügbar 


| cifs von vserver
erstellung von cifs-Freigaben von vserver
cifs-Freigabe von vserver: Löschen
vserver cifs shadowcopy anzeigen
cifs-Freigabe von vserver wird angezeigt
vserver cifs zeigen
vserver Exportrichtlinie
Erstellung von vserver Exportrichtlinien
vserver: Löschen der Exportrichtlinie
Erstellung von vserver Export-Policy-Regel
vserver: Export-Policy-Regel anzeigen
vserver Export-Policy wird angezeigt
vserver iscsi
vserver iscsi-Verbindung wird angezeigt
vserver zeigen
Netzwerkschnittstelle
Failover-Gruppen für Netzwerkschnittstellen
Netzwerkschnittstelle wird angezeigt 
|===
|===
| Schreibgeschützter Befehl: Mindestberechtigungen für ONTAP 8.3 und höher erforderlich 


| vserver
vserver Peer 
|===

NOTE: Sie können die Warnmeldungen zu den nicht unterstützten vServer-Befehlen ignorieren.



== Weitere ONTAP-Informationen

* Wenn Sie ONTAP 8.2.x verwenden:
+
Sie müssen sich als anmelden `vsadmin` Auf der Storage-VM die entsprechenden Berechtigungen für das SnapCenter-Plug-in für den Betrieb von VMware vSphere.

* Wenn Sie ONTAP 8.3 und höher verwenden:
+
Sie müssen sich als anmelden `vsadmin` Oder mit einer Rolle, die die in den obigen Tabellen aufgeführten Mindestberechtigungen hat.

* Sie müssen der Cluster-Administrator sein, um Benutzerrollen zu erstellen und zu managen. Sie können die Benutzer entweder der Cluster Storage VM oder der Storage VM zuordnen.

